#!/bin/bash

# Usage: ./bump-version 2.8.awesome

NEW_VERSION="$1"
find plugins -name MANIFEST.MF -or -name feature.xml |
    xargs perl -i -lpe '
        BEGIN { $l = 0 }
        if (/^Bundle-Version:/) {
            $_ = "Bundle-Version: '$NEW_VERSION'"
        }
        elsif (/^(\s+)version="/ && !$l++) {
            $_ = $1 . q[version="'$NEW_VERSION'"]
        }'
