CREATE TABLE Folder (
	id         VARCHAR(36) NOT NULL,
    name       VARCHAR(50) NOT NULL,
	baseObject VARCHAR(36) NOT NULL,

	PRIMARY KEY (id)
);

ALTER TABLE Folder ADD UNIQUE (id);
ALTER TABLE Folder ADD UNIQUE (name); 
ALTER TABLE Folder ADD FOREIGN KEY (baseObject) REFERENCES BaseObject(id) ON DELETE CASCADE;
